kind: pipeline
name: build-release

steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_DEFAULT_REGION: us-east-1
    secret_key:
      from_secret: aws_secret_access_key
    repo: username/repository
    registry: docker-or-ecr-link
    build_args_from_env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    build_args:
      - AWS_DEFAULT_REGION=us-east-1
    tags:
      - ${DRONE_BRANCH}
  when:
    branch:
    - release-*

- name: update-status-to-github
  image: codehimanshu/gitdrone:1.6
  environment:
    DRONE_PULL_REQUEST: ${DRONE_PULL_REQUEST}
    DRONE_REPO_OWNER: ${DRONE_REPO_NAMESPACE}
    DRONE_REPO_NAME: ${DRONE_REPO_NAME}
    DRONE_ACCESS_TOKEN:
      from_secret: DRONE_ACCESS_TOKEN
    DRONE_HOST: ${DRONE_SYSTEM_HOST}
    DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    GITHUB_INSTALLATION_ID:
      from_secret: GITHUB_INSTALLATION_ID
    GITHUB_APP_ID:
      from_secret: GITHUB_APP_ID
    PRIVATE_KEY:
      from_secret: PRIVATE_KEY
  when:
    status: [ failure ]
    branch:
    - release-*
