kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - go build
  - go test
- name: Build Docker image 
  image: alpine/git
  commands:
  - git clone git@github.com:yazanmonshed/webdev_golang.git
  - git checkout $DRONE_COMMIT
- name: build
  image: golang
  commands:
  - go build
  - go test