kind: pipeline
type: docker
name: goapp service

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: yazanmonshed/goapp
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - dev
